-- NextLove — Seed : 15 faux profils réalistes
-- Insérés avec service_role (bypass RLS)

INSERT INTO public.users (
  id, name, age, gender, looking_for, about, lifestyle, relation_type,
  kids, religion, smoke, drink, education, values, photos, location,
  is_premium, is_verified, is_active, questionnaire_data
) VALUES

(uuid_generate_v4(), 'Sophie', 28, 'woman', 'man',
 'Architecte le jour, exploratrice la nuit. J''adore les musées, les festivals et les voyages improvisés.',
 'Équilibré', 'serious', 'want', 'Aucune', 'never', 'socially', 'masters',
 ARRAY['Fumeur','Alcool fréquent'], ARRAY['https://randomuser.me/api/portraits/women/44.jpg'],
 '{"city":"Paris","lat":48.8566,"lng":2.3522}',
 false, true, true,
 '{"firstName":"Sophie","age":28,"city":"Paris","job":"Architecte","education":"bac5","personality":"ambivert","dominantTrait":"creative","humorLevel":7,"communication":"Direct","attachment":"Secure","religion":"Aucune","politics":"Gauche","familyImportance":8,"ambitionLevel":9,"honestyLevel":9,"lifestyle":"Équilibré","sports":"Régulier","alcohol":"Occasionnel","smoking":"Non fumeur","diet":"Omnivore","pets":"J adore","partnerAgeMin":26,"partnerAgeMax":36,"maxDistance":50,"appearanceImportance":6,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["smoker","heavy_drinker"]}'),

(uuid_generate_v4(), 'Emma', 25, 'woman', 'man',
 'Photographe freelance passionnée par la nature. Je rêve de faire le tour du monde avec un sac à dos.',
 'Actif', 'serious', 'open', 'Spirituel', 'never', 'never', 'bachelors',
 ARRAY['Valeurs très différentes'], ARRAY['https://randomuser.me/api/portraits/women/68.jpg'],
 '{"city":"Lyon","lat":45.7640,"lng":4.8357}',
 false, true, true,
 '{"firstName":"Emma","age":25,"city":"Lyon","job":"Photographe","education":"bac3","personality":"introvert","dominantTrait":"adventurer","humorLevel":8,"communication":"Émotionnel","attachment":"Secure","religion":"Spirituel","politics":"Apolitique","familyImportance":6,"ambitionLevel":7,"honestyLevel":10,"lifestyle":"Actif","sports":"Régulier","alcohol":"Non","smoking":"Non fumeur","diet":"Végétarien","pets":"J adore","partnerAgeMin":23,"partnerAgeMax":32,"maxDistance":100,"appearanceImportance":5,"partnerEducation":"bac3","childrenOk":"Indifférent","dealBreakers":["different_values"]}'),

(uuid_generate_v4(), 'Camille', 30, 'woman', 'man',
 'Médecin urgentiste et marathonienne. La vie est courte, il faut en profiter. Fan de jazz et bonne cuisine.',
 'Actif', 'serious', 'want', 'Aucune', 'never', 'socially', 'phd',
 ARRAY['Relation non sérieuse','Fumeur'], ARRAY['https://randomuser.me/api/portraits/women/32.jpg'],
 '{"city":"Bordeaux","lat":44.8378,"lng":-0.5792}',
 true, true, true,
 '{"firstName":"Camille","age":30,"city":"Bordeaux","job":"Médecin","education":"doctorate","personality":"extravert","dominantTrait":"empathic","humorLevel":6,"communication":"Direct","attachment":"Secure","religion":"Aucune","politics":"Centre","familyImportance":7,"ambitionLevel":10,"honestyLevel":10,"lifestyle":"Actif","sports":"Intensif","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J aime","partnerAgeMin":28,"partnerAgeMax":40,"maxDistance":30,"appearanceImportance":7,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["casual_only","smoker"]}'),

(uuid_generate_v4(), 'Léa', 26, 'woman', 'man',
 'Développeuse web le jour, danseuse salsa la nuit. Je cherche quelqu''un qui sait rire et danser sous la pluie.',
 'Équilibré', 'casual', 'open', 'Aucune', 'never', 'socially', 'masters',
 ARRAY['Infidélité passée'], ARRAY['https://randomuser.me/api/portraits/women/79.jpg'],
 '{"city":"Marseille","lat":43.2965,"lng":5.3698}',
 false, true, true,
 '{"firstName":"Léa","age":26,"city":"Marseille","job":"Développeuse Web","education":"bac5","personality":"extravert","dominantTrait":"adventurer","humorLevel":9,"communication":"Direct","attachment":"Anxieux","religion":"Aucune","politics":"Gauche","familyImportance":7,"ambitionLevel":8,"honestyLevel":8,"lifestyle":"Équilibré","sports":"Occasionnel","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J aime","partnerAgeMin":24,"partnerAgeMax":34,"maxDistance":50,"appearanceImportance":7,"partnerEducation":"bac3","childrenOk":"Indifférent","dealBreakers":["infidelity"]}'),

(uuid_generate_v4(), 'Marie', 29, 'woman', 'man',
 'Ingénieure aérospatiale passionnée par les étoiles. Je crois aux grandes aventures et aux petits bonheurs.',
 'Équilibré', 'serious', 'want', 'Croyant', 'never', 'socially', 'masters',
 ARRAY['Alcool fréquent','Fumeur'], ARRAY['https://randomuser.me/api/portraits/women/21.jpg'],
 '{"city":"Toulouse","lat":43.6047,"lng":1.4442}',
 false, true, true,
 '{"firstName":"Marie","age":29,"city":"Toulouse","job":"Ingénieure Aérospatiale","education":"bac5","personality":"introvert","dominantTrait":"rational","humorLevel":6,"communication":"Factuel","attachment":"Secure","religion":"Croyant","politics":"Centre","familyImportance":6,"ambitionLevel":10,"honestyLevel":9,"lifestyle":"Équilibré","sports":"Occasionnel","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"Neutre","partnerAgeMin":27,"partnerAgeMax":37,"maxDistance":80,"appearanceImportance":5,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["heavy_drinker","smoker"]}'),

(uuid_generate_v4(), 'Julie', 27, 'woman', 'man',
 'Professeure d''art et créatrice dans l''âme. J''aime les personnes authentiques avec une vraie passion.',
 'Casanier', 'serious', 'have', 'Spirituel', 'never', 'never', 'masters',
 ARRAY['Relation non sérieuse'], ARRAY['https://randomuser.me/api/portraits/women/55.jpg'],
 '{"city":"Nantes","lat":47.2184,"lng":-1.5536}',
 false, true, true,
 '{"firstName":"Julie","age":27,"city":"Nantes","job":"Professeure Art","education":"bac5","personality":"introvert","dominantTrait":"creative","humorLevel":7,"communication":"Émotionnel","attachment":"Secure","religion":"Spirituel","politics":"Gauche","familyImportance":9,"ambitionLevel":7,"honestyLevel":10,"lifestyle":"Casanier","sports":"Occasionnel","alcohol":"Non","smoking":"Non fumeur","diet":"Végétarien","pets":"J adore","partnerAgeMin":25,"partnerAgeMax":35,"maxDistance":40,"appearanceImportance":4,"partnerEducation":"bac3","childrenOk":"Oui","dealBreakers":["casual_only"]}'),

(uuid_generate_v4(), 'Chloé', 31, 'woman', 'man',
 'Cheffe cuisinière étoilée et voyageuse. Ma passion : marier les saveurs du monde entier.',
 'Actif', 'serious', 'open', 'Aucune', 'never', 'socially', 'bachelors',
 ARRAY['Pas de sport'], ARRAY['https://randomuser.me/api/portraits/women/12.jpg'],
 '{"city":"Nice","lat":43.7102,"lng":7.2620}',
 true, true, true,
 '{"firstName":"Chloé","age":31,"city":"Nice","job":"Cheffe Cuisinière","education":"bac3","personality":"extravert","dominantTrait":"adventurer","humorLevel":8,"communication":"Direct","attachment":"Secure","religion":"Aucune","politics":"Apolitique","familyImportance":8,"ambitionLevel":9,"honestyLevel":8,"lifestyle":"Actif","sports":"Régulier","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J aime","partnerAgeMin":28,"partnerAgeMax":42,"maxDistance":100,"appearanceImportance":7,"partnerEducation":"bac","childrenOk":"Indifférent","dealBreakers":["no_sport"]}'),

(uuid_generate_v4(), 'Anaïs', 24, 'woman', 'man',
 'Étudiante en droit européen, passionnée de politique et de langues. Je parle 4 langues.',
 'Équilibré', 'serious', 'dont_want', 'Aucune', 'never', 'socially', 'bachelors',
 ARRAY['Enfants déjà','Veut des enfants'], ARRAY['https://randomuser.me/api/portraits/women/91.jpg'],
 '{"city":"Strasbourg","lat":48.5734,"lng":7.7521}',
 false, true, true,
 '{"firstName":"Anaïs","age":24,"city":"Strasbourg","job":"Étudiante en Droit","education":"bac3","personality":"extravert","dominantTrait":"rational","humorLevel":7,"communication":"Diplomatique","attachment":"Secure","religion":"Aucune","politics":"Centre","familyImportance":8,"ambitionLevel":10,"honestyLevel":9,"lifestyle":"Équilibré","sports":"Occasionnel","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"Neutre","partnerAgeMin":22,"partnerAgeMax":30,"maxDistance":60,"appearanceImportance":6,"partnerEducation":"bac3","childrenOk":"Non","dealBreakers":["has_children","wants_children"]}'),

(uuid_generate_v4(), 'Clara', 33, 'woman', 'man',
 'Directrice marketing, yogini le week-end. Je cherche quelqu''un de curieux et bienveillant.',
 'Équilibré', 'serious', 'open', 'Spirituel', 'never', 'socially', 'masters',
 ARRAY['Alcool fréquent','Fumeur'], ARRAY['https://randomuser.me/api/portraits/women/28.jpg'],
 '{"city":"Paris","lat":48.8566,"lng":2.3522}',
 true, true, true,
 '{"firstName":"Clara","age":33,"city":"Paris","job":"Directrice Marketing","education":"bac5","personality":"ambivert","dominantTrait":"empathic","humorLevel":8,"communication":"Diplomatique","attachment":"Secure","religion":"Spirituel","politics":"Gauche","familyImportance":8,"ambitionLevel":9,"honestyLevel":9,"lifestyle":"Équilibré","sports":"Régulier","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J adore","partnerAgeMin":30,"partnerAgeMax":42,"maxDistance":30,"appearanceImportance":6,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["heavy_drinker","smoker"]}'),

(uuid_generate_v4(), 'Inès', 27, 'woman', 'man',
 'Journaliste et globe-trotteuse. Les histoires des gens me fascinent. Amateur de concerts et de street food.',
 'Actif', 'casual', 'open', 'Aucune', 'sometimes', 'socially', 'masters',
 ARRAY['Infidélité passée'], ARRAY['https://randomuser.me/api/portraits/women/39.jpg'],
 '{"city":"Paris","lat":48.8566,"lng":2.3522}',
 false, true, true,
 '{"firstName":"Inès","age":27,"city":"Paris","job":"Journaliste","education":"bac5","personality":"extravert","dominantTrait":"adventurer","humorLevel":9,"communication":"Direct","attachment":"Anxieux","religion":"Aucune","politics":"Gauche","familyImportance":5,"ambitionLevel":8,"honestyLevel":9,"lifestyle":"Actif","sports":"Occasionnel","alcohol":"Socially","smoking":"Occasionnel","diet":"Omnivore","pets":"J aime","partnerAgeMin":25,"partnerAgeMax":35,"maxDistance":100,"appearanceImportance":7,"partnerEducation":"bac3","childrenOk":"Indifférent","dealBreakers":["infidelity"]}'),

(uuid_generate_v4(), 'Lucie', 29, 'woman', 'man',
 'Vétérinaire passionnée par les animaux et la nature. Randonneuse le week-end, cuisinière du dimanche.',
 'Équilibré', 'serious', 'want', 'Croyant', 'never', 'socially', 'phd',
 ARRAY['Fumeur','Pas de sport'], ARRAY['https://randomuser.me/api/portraits/women/15.jpg'],
 '{"city":"Grenoble","lat":45.1885,"lng":5.7245}',
 false, true, true,
 '{"firstName":"Lucie","age":29,"city":"Grenoble","job":"Vétérinaire","education":"doctorate","personality":"introvert","dominantTrait":"empathic","humorLevel":7,"communication":"Émotionnel","attachment":"Secure","religion":"Croyant","politics":"Centre","familyImportance":9,"ambitionLevel":7,"honestyLevel":10,"lifestyle":"Équilibré","sports":"Régulier","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J adore","partnerAgeMin":27,"partnerAgeMax":38,"maxDistance":60,"appearanceImportance":5,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["smoker","no_sport"]}'),

(uuid_generate_v4(), 'Manon', 23, 'woman', 'man',
 'Étudiante en design graphique, passionnée de typographie et de musique indie. Toujours un carnet de croquis dans le sac.',
 'Casanier', 'casual', 'dont_want', 'Aucune', 'never', 'socially', 'bachelors',
 ARRAY['Relation non sérieuse'], ARRAY['https://randomuser.me/api/portraits/women/63.jpg'],
 '{"city":"Lille","lat":50.6292,"lng":3.0573}',
 false, false, true,
 '{"firstName":"Manon","age":23,"city":"Lille","job":"Étudiante Design","education":"bac3","personality":"introvert","dominantTrait":"creative","humorLevel":8,"communication":"Émotionnel","attachment":"Anxieux","religion":"Aucune","politics":"Gauche","familyImportance":4,"ambitionLevel":7,"honestyLevel":8,"lifestyle":"Casanier","sports":"Non","alcohol":"Socially","smoking":"Non fumeur","diet":"Végétarien","pets":"J adore","partnerAgeMin":21,"partnerAgeMax":28,"maxDistance":30,"appearanceImportance":7,"partnerEducation":"bac","childrenOk":"Non","dealBreakers":["casual_only"]}'),

(uuid_generate_v4(), 'Sarah', 32, 'woman', 'man',
 'Avocate en droit des affaires le jour, pianiste le soir. La musique et la justice sont mes deux passions.',
 'Actif', 'serious', 'open', 'Aucune', 'never', 'socially', 'masters',
 ARRAY['Fumeur','Alcool fréquent'], ARRAY['https://randomuser.me/api/portraits/women/47.jpg'],
 '{"city":"Lyon","lat":45.7640,"lng":4.8357}',
 true, true, true,
 '{"firstName":"Sarah","age":32,"city":"Lyon","job":"Avocate","education":"bac5","personality":"ambivert","dominantTrait":"rational","humorLevel":7,"communication":"Direct","attachment":"Secure","religion":"Aucune","politics":"Centre","familyImportance":7,"ambitionLevel":10,"honestyLevel":10,"lifestyle":"Actif","sports":"Occasionnel","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"Neutre","partnerAgeMin":30,"partnerAgeMax":42,"maxDistance":40,"appearanceImportance":6,"partnerEducation":"bac5","childrenOk":"Indifférent","dealBreakers":["smoker","heavy_drinker"]}'),

(uuid_generate_v4(), 'Alice', 26, 'woman', 'man',
 'Kinésithérapeute, runner du dimanche et grande amoureuse des voyages en van. La liberté avant tout.',
 'Actif', 'serious', 'want', 'Aucune', 'never', 'socially', 'masters',
 ARRAY['Infidélité passée','Fumeur'], ARRAY['https://randomuser.me/api/portraits/women/82.jpg'],
 '{"city":"Montpellier","lat":43.6108,"lng":3.8767}',
 false, true, true,
 '{"firstName":"Alice","age":26,"city":"Montpellier","job":"Kinésithérapeute","education":"bac5","personality":"extravert","dominantTrait":"adventurer","humorLevel":8,"communication":"Direct","attachment":"Secure","religion":"Aucune","politics":"Apolitique","familyImportance":7,"ambitionLevel":8,"honestyLevel":9,"lifestyle":"Actif","sports":"Intensif","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J adore","partnerAgeMin":24,"partnerAgeMax":34,"maxDistance":80,"appearanceImportance":7,"partnerEducation":"bac3","childrenOk":"Oui","dealBreakers":["infidelity","smoker"]}'),

(uuid_generate_v4(), 'Noémie', 34, 'woman', 'man',
 'Cheffe de projet IT, maman solo et amoureuse de la vie. Je cherche quelqu''un de solide et bienveillant.',
 'Équilibré', 'serious', 'have', 'Croyant', 'never', 'socially', 'masters',
 ARRAY['Alcool fréquent','Infidélité passée'], ARRAY['https://randomuser.me/api/portraits/women/57.jpg'],
 '{"city":"Rennes","lat":48.1173,"lng":-1.6778}',
 false, true, true,
 '{"firstName":"Noémie","age":34,"city":"Rennes","job":"Cheffe de Projet IT","education":"bac5","personality":"ambivert","dominantTrait":"empathic","humorLevel":7,"communication":"Diplomatique","attachment":"Secure","religion":"Croyant","politics":"Centre","familyImportance":10,"ambitionLevel":8,"honestyLevel":10,"lifestyle":"Équilibré","sports":"Occasionnel","alcohol":"Socially","smoking":"Non fumeur","diet":"Omnivore","pets":"J aime","partnerAgeMin":30,"partnerAgeMax":44,"maxDistance":50,"appearanceImportance":5,"partnerEducation":"bac5","childrenOk":"Oui","dealBreakers":["heavy_drinker","infidelity"]}')

ON CONFLICT (id) DO NOTHING;
